### PR TITLE
Hover effects for all links on frontpage

### PR DESCRIPTION
**Pull request by Benjaneb**

### CODE REVIEW

**Review by foodelevator — COMMENTED** [review]
[Screencast from 2024-06-22 20-09-57.webm](https://github.com/datasektionen/bawang/assets/32957299/604d5e2d-196e-409d-999e-a3841f50ebe3)

Not the biggest fan of this one.

I'm also not that fond of the "button-like" links getting bigger but I bet I would like it on a screen with higher resolution so idk

**Comment by foodelevator** [comment]
Also, the news get lighter gray which feel backwards to me and I think it looks nicer if they get a bit darker instead

**Comment by Benjaneb** [comment]
The English link was apparently a Bootstrap rule suddenly being applied after my recent updates, so fixed that. Also, yeah, the news link looks much better getting dark on hover since it's already pretty light. The "button-like's" getting bigger didn't look half-bad but I made them get lighter instead.

**Review by foodelevator — APPROVED** [review]
Looks good!

**Pull request merged**
